### ISSUE TITLE
Example missing from /samples-demos

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/barcode-reader-docs-js#375]
Missing example from Use Case - [Show Result Texts on the Video](https://demo.dynamsoft.com/Samples/DBR/JS/use-case/show-result-texts-on-the-video.html)

Location: https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/samples-demos/index.html
Please refer to: https://demo.dynamsoft.com/Samples/DBR/JS/

**Comment by Tom-Dynamsoft** [comment]
@a362758199  Please update the page https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/samples-demos/index.html based on the latest index https://demo.dynamsoft.com/Samples/DBR/JS/

**Comment by a362758199** [comment]
Updated [this page](https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/samples-demos/index.html)
@felixindynamsoft And find a 404 link on Github index page, please help review the [PR](https://github.com/Dynamsoft/barcode-reader-javascript-samples/pull/206)
