### ISSUE TITLE
Tooltips on feedback and hide menu icon button

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/barcode-reader-docs-js#377]
Icon buttons that have no text, such as the `edit docs` and `hide menu` button, should have tooltips to show what they do.
Additionally, we should confirm that all icon buttons have `cursor: pointer` on them.

![image](https://github.com/dynamsoft-docs/barcode-reader-docs-js/assets/172628627/390542ed-e186-451a-853e-2bad4ace9462)

**Comment by Tom-Dynamsoft** [comment]
I mentioned the issue to the doc 2.0 group. We should first add tooltips and ensure all icon buttons have a cursor: pointer. Then we can also think about how to make these buttons more obvious

**Comment by JianiHe0613** [comment]
Fixed.
