### ISSUE TITLE
Incorrect link from `CapturedResult`

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/barcode-reader-docs-js#378]
Location: `L52` on https://github.com/dynamsoft-docs/capture-vision-docs-js/blob/main/programming/javascript/api-reference/capture-vision-router/captured-result-receiver.md?plain=1

CapturedResult links to 404 page. Should link to https://www.dynamsoft.com/capture-vision/docs/web/programming/javascript/api-reference/capture-vision-router/interfaces/captured-result.html?product=dbr&lang=javascript

Ref: https://www.dynamsoft.com/capture-vision/docs/web/programming/javascript/api-reference/capture-vision-router/captured-result-receiver.html?product=dbr&lang=javascript#oncapturedresultreceived

**Comment by Tom-Dynamsoft** [comment]
Fixed in commit [#25](https://github.com/dynamsoft-docs/capture-vision-docs-js/pull/25)
