### ISSUE TITLE
[Bug] Upgrade guides contains incorrect hyperlinks

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/barcode-reader-docs-js#382]
Link: https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/upgrade-guide/9to10.html#migrate-your-templates

On https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/upgrade-guide/9to10.html#change-the-way-to-reference-the-sdk, there are some incorrect hyperlinks found

eg.
![image](https://github.com/dynamsoft-docs/barcode-reader-docs-js/assets/172628627/3d5f50e0-9819-474a-9fee-faf111be5e3c)
- [ImageParameter.GrayscaleTransformationModes](https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/upgrade-guide/image-parameter/grayscale-enhancement-modes.html?product=dbr&repoType=core)

**Comment by a362758199** [comment]
Fixed. Thanks for your report
