### ISSUE TITLE
[Enhancement] Insert updated sample guide links to outdated guides

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/barcode-reader-docs-js#385]
Some guides that shows up on Google are using outdated versions of DBR JS.
We should include a link/indicator that links to the latest version of DBR JS guides.

Reference: [barcode-reader-docs-js/programming-old/javascript/samples-demos at main · dynamsoft-docs/barcode-reader-docs-js (github.com)](https://github.com/dynamsoft-docs/barcode-reader-docs-js/tree/main/programming-old/javascript/samples-demos)
![image](https://github.com/dynamsoft-docs/barcode-reader-docs-js/assets/172628627/0557bb34-e6e8-4306-be21-8af955a39160)

We have done this before
![image](https://github.com/dynamsoft-docs/barcode-reader-docs-js/assets/172628627/ab301120-5f20-4d2b-9474-f2cbcd2d6f65)

**Comment by Tom-Dynamsoft** [comment]
Adding a logic to show the warning message and the redirect link. Will gradually add these fields to these pages.

**Comment by Tom-Dynamsoft** [comment]
Logic added and this page now has the warning & correct redirect link. Will add the same in other pages too.
