### ISSUE TITLE
Set scan region in Getting Started docs improvements

### ISSUE THREAD

**Issue by felixindynamsoft** [dynamsoft-docs/barcode-reader-docs-js#390]
A member of our TST team mentioned that setting the scan region section in the docs could be improved for clarity.
In DBR v9x, setting the ROI will show the outline of the scan region, but not in DBR v10.
The outline will only show when we set scan region through camera enhancer

Possible solutions
- Add a parameter to enable showing outlines when setting the ROI
- Similar to our core documentation, separate using the ROI for reading images, and using setScanRegion on camera enhancer for reading videos  (https://www.dynamsoft.com/barcode-reader/docs/core/programming/features/barcode-scan-region-mobile.html?lang=objc,swift)

Documentation Link: https://www.dynamsoft.com/barcode-reader/docs/web/programming/javascript/user-guide/index.html#specify-a-scan-region

**Comment by Tom-Dynamsoft** [comment]
Improved/simplified in commits https://github.com/dynamsoft-docs/barcode-reader-docs-js/commit/a6a5859947817ab2797dac71ae284dab3c040b38 and https://github.com/dynamsoft-docs/barcode-reader-docs-js/commit/612a1f281099a7cace4bcdc2102cfd78e0ce25ea
